CREATE TABLE Contato (
    ID NUMERIC(14,0) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    IDADE NUMERIC(3,0) NOT NULL
);

CREATE TABLE Telefone (
    IDCONTATO NUMERIC(14,0) NOT NULL,
    ID NUMERIC(14,0) NOT NULL,
    NUMERO VARCHAR(16) NOT NULL,
    PRIMARY KEY (IDCONTATO, ID),
    CONSTRAINT fk_contato_id FOREIGN KEY (IDCONTATO) REFERENCES Contato(ID)
);
